from __future__ import annotations

from typing import Any


def runtime_v5_diagnostics_snapshot_base(
    *,
    runtime_summary: dict[str, Any],
    current_capability_readiness: dict[str, Any],
    pending_action: dict[str, Any],
    pending_approval: dict[str, Any],
    pending_cleanup: dict[str, Any],
    current_approval: dict[str, Any],
    result_context_events: list[dict[str, Any]],
    capability_summary: dict[str, Any],
    provider_registry: dict[str, Any],
    runtime_provider_snapshot: dict[str, Any],
    action_trace: list[dict[str, Any]],
    decision_trace: list[dict[str, Any]],
) -> dict[str, Any]:
    return {
        "diagnostics_version": runtime_summary.get("diagnostics_version") if isinstance(runtime_summary, dict) else "",
        "diagnostics_capabilities": runtime_summary.get("diagnostics_capabilities") if isinstance(runtime_summary, dict) else {},
        "health": runtime_summary.get("health") if isinstance(runtime_summary, dict) else {},
        "runtime_mode": runtime_summary.get("runtime_mode") if isinstance(runtime_summary, dict) else "full_runtime",
        "runtime_path_kind": runtime_summary.get("runtime_path_kind") if isinstance(runtime_summary, dict) else "v5_pipeline",
        "bypass_reason": runtime_summary.get("bypass_reason") if isinstance(runtime_summary, dict) else "",
        "current_path_maturity": runtime_summary.get("current_path_maturity") if isinstance(runtime_summary, dict) else {},
        "current_capability_readiness": current_capability_readiness,
        "debug_locator": runtime_summary.get("debug_locator") if isinstance(runtime_summary, dict) else {},
        "snapshot_summary": runtime_summary.get("snapshot_summary") if isinstance(runtime_summary, dict) else {},
        "snapshot_lifecycle": runtime_summary.get("snapshot_lifecycle") if isinstance(runtime_summary, dict) else {},
        "evidence_summary": runtime_summary.get("evidence_summary") if isinstance(runtime_summary, dict) else {},
        "runtime_gate": runtime_summary.get("runtime_gate") if isinstance(runtime_summary, dict) else {},
        "repair_plan": runtime_summary.get("repair_plan") if isinstance(runtime_summary, dict) else {},
        "health_matrix": runtime_summary.get("health_matrix") if isinstance(runtime_summary, dict) else {},
        "constitution_guard": runtime_summary.get("constitution_guard") if isinstance(runtime_summary, dict) else {},
        "intent": runtime_summary.get("intent") if isinstance(runtime_summary, dict) else "",
        "strategy": runtime_summary.get("strategy") if isinstance(runtime_summary, dict) else "",
        "sources": runtime_summary.get("sources") if isinstance(runtime_summary, dict) else [],
        "result_context": runtime_summary.get("result_context") if isinstance(runtime_summary, dict) else {},
        "result_context_event_summary": runtime_summary.get("result_context_event_summary") if isinstance(runtime_summary, dict) else {},
        "result_context_quality": runtime_summary.get("result_context_quality") if isinstance(runtime_summary, dict) else {},
        "permission": runtime_summary.get("permission") if isinstance(runtime_summary, dict) else {},
        "permission_health": runtime_summary.get("permission_health") if isinstance(runtime_summary, dict) else {},
        "context_health": runtime_summary.get("context_health") if isinstance(runtime_summary, dict) else {},
        "profile_health": runtime_summary.get("profile_health") if isinstance(runtime_summary, dict) else {},
        "followup_health": runtime_summary.get("followup_health") if isinstance(runtime_summary, dict) else {},
        "followup_consume_contract": runtime_summary.get("followup_consume_contract") if isinstance(runtime_summary, dict) else {},
        "decision_health": runtime_summary.get("decision_health") if isinstance(runtime_summary, dict) else {},
        "router_health": runtime_summary.get("router_health") if isinstance(runtime_summary, dict) else {},
        "execution_health": runtime_summary.get("execution_health") if isinstance(runtime_summary, dict) else {},
        "answer_health": runtime_summary.get("answer_health") if isinstance(runtime_summary, dict) else {},
        "decision_summary": runtime_summary.get("decision_summary") if isinstance(runtime_summary, dict) else {},
        "answer_metadata": runtime_summary.get("answer_metadata") if isinstance(runtime_summary, dict) else {},
        "pending_action": pending_action,
        "pending_approval": pending_approval,
        "pending_cleanup": pending_cleanup,
        "current_approval": current_approval,
        "provider_results": runtime_summary.get("provider_results") if isinstance(runtime_summary, dict) else [],
        "provider_summary": runtime_summary.get("provider_summary") if isinstance(runtime_summary, dict) else {},
        "source_execution_contract": runtime_summary.get("source_execution_contract") if isinstance(runtime_summary, dict) else {},
        "pipeline_frames": runtime_summary.get("pipeline_frames") if isinstance(runtime_summary, dict) else [],
        "pipeline_health": runtime_summary.get("pipeline_health") if isinstance(runtime_summary, dict) else {},
        "pipeline_constitution_contract": runtime_summary.get("pipeline_constitution_contract") if isinstance(runtime_summary, dict) else {},
        "pipeline_timing": runtime_summary.get("pipeline_timing") if isinstance(runtime_summary, dict) else {},
        "timing_health": runtime_summary.get("timing_health") if isinstance(runtime_summary, dict) else {},
        "result_context_events": result_context_events,
        "capability_summary": capability_summary,
        "provider_registry": provider_registry,
        "runtime_provider_snapshot": runtime_provider_snapshot,
        "action_trace": action_trace,
        "action_timeline": runtime_summary.get("action_timeline") if isinstance(runtime_summary, dict) else {},
        "action_closure": runtime_summary.get("action_closure") if isinstance(runtime_summary, dict) else {},
        "decision_trace": decision_trace,
    }
